Repository diogoazevedos/nginx-vod-module, pull requests merged in 2025-07, with the labels that each got.

#42 Add multi-DRM support for HLS SAMPLE-AES-CTR
  README.md
  config
  demo/drm/tears-of-steel
  ngx_http_vod_dash.c
  ngx_http_vod_hls.c
  sample/nginx.conf
  vod/dash/dash_packager.c
  vod/dash/edash_packager.c
  vod/dash/edash_packager.h
  vod/hls/hls_encryption.h
  vod/hls/m3u8_builder.c
  vod/manifest_utils.c
  vod/mp4/mp4_pssh.c
  vod/mp4/mp4_pssh.h
Labels: enhancement

#44 Fix `vod_dash_fragment_file_name_prefix` default value
  README.md
Labels: documentation

#45 Remove `libxml2` deprecation error
  vod/subtitle/dfxp_format.c
Labels: bug

#46 Add HLS session key support
  ngx_http_vod_hls.c
  vod/hls/m3u8_builder.c
  vod/hls/m3u8_builder.h
Labels: enhancement

#47 Build against stable and mainline nginx
  .github/workflows/main.yml
  Dockerfile
Labels: cosmetic

#50 Parameterize nginx version via docker build
  Dockerfile
Labels: cosmetic
